In [46]:
import pandas as pd;
df = pd.read_csv("Airbnb_Open_Data.csv");
# print(df.tail(5));
# print(df.head(5))
# print(df);
# print(df['license'])
print(df.info())

C:\Users\PARTH\AppData\Local\Temp\ipykernel_24052\4149488092.py:2: DtypeWarning: Columns (0: license) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Airbnb_Open_Data.csv");

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  str
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host name                       102193 non-null  str
 5   neighbourhood group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country code                    102468 non-null  str
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  str
 13  room type                       102599 non-null  str
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  str
 16  service fee                     102326 non-null  str
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   str
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   str
 25  license                         2 non-null       str
dtypes: float64(9), int64(2), object(1), str(14)
memory usage: 20.4+ MB
None

In [47]:
df['license'];
# print(df);
print(df.columns);

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

In [48]:
columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review',];
columns_to_drop = ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'];

In [51]:
len(columns_to_keep);

In [52]:
len(columns_to_drop);

In [53]:
df[columns_to_keep];

In [38]:
df[columns_to_drop];

In [39]:
df.shape

(102599, 26)

2nd method dropping columns

In [54]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

2 Method Dropping COlumns

In [58]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules'],
      dtype='str')

In [ ]:
df.drop(columns=columns_to_drop,inplace=True);

In [62]:
df.shape

(102599, 25)

In [63]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules'],
      dtype='str')

In [69]:
df.rename(columns={"NAME":"Name"},inplace=True);
print(df)

             id                                              Name  \
0       1001254                Clean & quiet apt home by the park
1       1002102                             Skylit Midtown Castle
2       1002403               THE VILLAGE OF HARLEM....NEW YORK !
3       1002755                                               NaN
4       1003689  Entire Apt: Spacious Studio/Loft by central park
...         ...                                               ...
102594  6092437                        Spare room in Williamsburg
102595  6092990                     Best Location near Columbia U
102596  6093542                    Comfy, bright room in Brooklyn
102597  6094094                  Big Studio-One Stop from Midtown
102598  6094647                              585 sf Luxury Studio

            host id host_identity_verified    host name neighbourhood group  \
0       80014485718            unconfirmed     Madaline            Brooklyn
1       52335172823               verified        Jenna           Manhattan
2       78829239556                    NaN        Elise           Manhattan
3       85098326012            unconfirmed        Garry            Brooklyn
4       92037596077               verified       Lyndon           Manhattan
...             ...                    ...          ...                 ...
102594  12312296767               verified         Krik            Brooklyn
102595  77864383453            unconfirmed        Mifan           Manhattan
102596  69050334417            unconfirmed        Megan            Brooklyn
102597  11160591270            unconfirmed  Christopher              Queens
102598  68170633372            unconfirmed      Rebecca           Manhattan

              neighbourhood       lat      long        country  ...    price  \
0                Kensington  40.64749 -73.97237  United States  ...    $966
1                   Midtown  40.75362 -73.98377  United States  ...    $142
2                    Harlem  40.80902 -73.94190  United States  ...    $620
3              Clinton Hill  40.68514 -73.95976  United States  ...    $368
4               East Harlem  40.79851 -73.94399  United States  ...    $204
...                     ...       ...       ...            ...  ...      ...
102594         Williamsburg  40.70862 -73.94651  United States  ...    $844
102595  Morningside Heights  40.80460 -73.96545  United States  ...    $837
102596           Park Slope  40.67505 -73.98045  United States  ...    $988
102597     Long Island City  40.74989 -73.93777  United States  ...    $546
102598      Upper West Side  40.76807 -73.98342  United States  ...  $1,032

       service fee minimum nights number of reviews  last review  \
0            $193            10.0               9.0   10/19/2021
1             $28            30.0              45.0    5/21/2022
2            $124             3.0               0.0          NaN
3             $74            30.0             270.0     7/5/2019
4             $41            10.0               9.0   11/19/2018
...            ...            ...               ...          ...
102594       $169             1.0               0.0          NaN
102595       $167             1.0               1.0     7/6/2015
102596       $198             3.0               0.0          NaN
102597       $109             2.0               5.0   10/11/2015
102598       $206             1.0               0.0          NaN

       reviews per month review rate number  calculated host listings count  \
0                   0.21                4.0                             6.0
1                   0.38                4.0                             2.0
2                    NaN                5.0                             1.0
3                   4.64                4.0                             1.0
4                   0.10                3.0                             1.0
...                  ...                ...                             ...
102594               NaN                3.0                             1.0
102595              0.02                2.0                             2.0
102596               NaN                5.0                             1.0
102597              0.10                3.0                             1.0
102598               NaN                3.0                             1.0

        availability 365                                        house_rules
0                  286.0  Clean up and treat the home the way you'd like...
1                  228.0  Pet friendly but please confirm with me if the...
2                  352.0  I encourage you to use my kitchen, cooking and...
3                  322.0                                                NaN
4                  289.0  Please no smoking in the house, porch or on th...
...                  ...                                                ...
102594             227.0  No Smoking No Parties or Events of any kind Pl...
102595             395.0  House rules: Guests agree to the following ter...
102596             342.0                                                NaN
102597             386.0                                                NaN
102598              69.0                                                NaN

[102599 rows x 25 columns]

In [74]:
print(df.columns);

Index(['id', 'Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules'],
      dtype='str')

In [76]:
new_columns = [];
for i in df.columns:
     new_columns.append(i.upper());
print(new_columns)

['ID', 'NAME', 'HOST ID', 'HOST_IDENTITY_VERIFIED', 'HOST NAME', 'NEIGHBOURHOOD GROUP', 'NEIGHBOURHOOD', 'LAT', 'LONG', 'COUNTRY', 'COUNTRY CODE', 'INSTANT_BOOKABLE', 'CANCELLATION_POLICY', 'ROOM TYPE', 'CONSTRUCTION YEAR', 'PRICE', 'SERVICE FEE', 'MINIMUM NIGHTS', 'NUMBER OF REVIEWS', 'LAST REVIEW', 'REVIEWS PER MONTH', 'REVIEW RATE NUMBER', 'CALCULATED HOST LISTINGS COUNT', 'AVAILABILITY 365', 'HOUSE_RULES']

In [80]:
df.duplicated().sum();

In [ ]:
New_DataFrame_Modify =  df.copy();

             id                                              Name  \
0       1001254                Clean & quiet apt home by the park
1       1002102                             Skylit Midtown Castle
2       1002403               THE VILLAGE OF HARLEM....NEW YORK !
3       1002755                                               NaN
4       1003689  Entire Apt: Spacious Studio/Loft by central park
...         ...                                               ...
102594  6092437                        Spare room in Williamsburg
102595  6092990                     Best Location near Columbia U
102596  6093542                    Comfy, bright room in Brooklyn
102597  6094094                  Big Studio-One Stop from Midtown
102598  6094647                              585 sf Luxury Studio

            host id host_identity_verified    host name neighbourhood group  \
0       80014485718            unconfirmed     Madaline            Brooklyn
1       52335172823               verified        Jenna           Manhattan
2       78829239556                    NaN        Elise           Manhattan
3       85098326012            unconfirmed        Garry            Brooklyn
4       92037596077               verified       Lyndon           Manhattan
...             ...                    ...          ...                 ...
102594  12312296767               verified         Krik            Brooklyn
102595  77864383453            unconfirmed        Mifan           Manhattan
102596  69050334417            unconfirmed        Megan            Brooklyn
102597  11160591270            unconfirmed  Christopher              Queens
102598  68170633372            unconfirmed      Rebecca           Manhattan

              neighbourhood       lat      long        country  ...    price  \
0                Kensington  40.64749 -73.97237  United States  ...    $966
1                   Midtown  40.75362 -73.98377  United States  ...    $142
2                    Harlem  40.80902 -73.94190  United States  ...    $620
3              Clinton Hill  40.68514 -73.95976  United States  ...    $368
4               East Harlem  40.79851 -73.94399  United States  ...    $204
...                     ...       ...       ...            ...  ...      ...
102594         Williamsburg  40.70862 -73.94651  United States  ...    $844
102595  Morningside Heights  40.80460 -73.96545  United States  ...    $837
102596           Park Slope  40.67505 -73.98045  United States  ...    $988
102597     Long Island City  40.74989 -73.93777  United States  ...    $546
102598      Upper West Side  40.76807 -73.98342  United States  ...  $1,032

       service fee minimum nights number of reviews  last review  \
0            $193            10.0               9.0   10/19/2021
1             $28            30.0              45.0    5/21/2022
2            $124             3.0               0.0          NaN
3             $74            30.0             270.0     7/5/2019
4             $41            10.0               9.0   11/19/2018
...            ...            ...               ...          ...
102594       $169             1.0               0.0          NaN
102595       $167             1.0               1.0     7/6/2015
102596       $198             3.0               0.0          NaN
102597       $109             2.0               5.0   10/11/2015
102598       $206             1.0               0.0          NaN

       reviews per month review rate number  calculated host listings count  \
0                   0.21                4.0                             6.0
1                   0.38                4.0                             2.0
2                    NaN                5.0                             1.0
3                   4.64                4.0                             1.0
4                   0.10                3.0                             1.0
...                  ...                ...                             ...
102594               NaN                3.0                             1.0
102595              0.02                2.0                             2.0
102596               NaN                5.0                             1.0
102597              0.10                3.0                             1.0
102598               NaN                3.0                             1.0

        availability 365                                        house_rules
0                  286.0  Clean up and treat the home the way you'd like...
1                  228.0  Pet friendly but please confirm with me if the...
2                  352.0  I encourage you to use my kitchen, cooking and...
3                  322.0                                                NaN
4                  289.0  Please no smoking in the house, porch or on th...
...                  ...                                                ...
102594             227.0  No Smoking No Parties or Events of any kind Pl...
102595             395.0  House rules: Guests agree to the following ter...
102596             342.0                                                NaN
102597             386.0                                                NaN
102598              69.0                                                NaN

[102599 rows x 25 columns]

In [82]:
New_DataFrame_Modify.columns

Index(['id', 'Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules'],
      dtype='str')

In [ ]:
New_DataFrame_Modify.columns = new_columns;

In [83]:
New_DataFrame_Modify

,id,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and..."
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN

In [89]:
df.duplicated().value_counts()

False    102058
True        541
Name: count, dtype: int64

In [91]:
df.drop_duplicates(inplace=True);

In [92]:
df.duplicated().sum()

np.int64(0)

In [ ]:
"""
  Deleting redundant columns
  Renaming the columns
  dropping duplicates
  cleaning indivisual columns
  Remove nan value from dataset
  check for some more Transformations
"""

In [98]:
df.isna().sum();

In [105]:
df.dropna(inplace=True)

In [106]:
df.isna().sum()

id                                0
Name                              0
host id                           0
host_identity_verified            0
host name                         0
neighbourhood group               0
neighbourhood                     0
lat                               0
long                              0
country                           0
country code                      0
instant_bookable                  0
cancellation_policy               0
room type                         0
Construction year                 0
price                             0
service fee                       0
minimum nights                    0
number of reviews                 0
reviews per month                 0
review rate number                0
calculated host listings count    0
availability 365                  0
house_rules                       0
dtype: int64

In [107]:
df

,id,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,2020.0,$966,$193,10.0,9.0,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,2007.0,$142,$28,30.0,45.0,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,2009.0,$204,$41,10.0,9.0,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,2013.0,$577,$115,3.0,74.0,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs."
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,2009.0,"$1,060",$212,45.0,49.0,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102025,57349744,COZY Large Private APARTMENT in EAST VILLAGE,97186426683,verified,Luna,Manhattan,East Village,40.72588,-73.98598,United States,...,2003.0,$878,$176,6.0,22.0,0.87,2.0,1.0,15.0,"No Smoking, No Pets"
102028,57351400,"Gorgeous condo 20min from NYC,close to the air...",27226581142,unconfirmed,Arthur,Queens,Rego Park,40.72999,-73.86043,United States,...,2008.0,$994,$199,2.0,67.0,2.58,5.0,1.0,278.0,1. Be respectful of me and my home 2. No Pets ...
102029,57351953,Cozy room in a 2B with backyard access,5155155913,unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,...,2018.0,$822,$164,1.0,9.0,0.91,3.0,1.0,0.0,I have other roommates so be respectful of that.
102031,57353057,Cozy bedroom in williamsburg,83101851929,verified,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,...,2020.0,"$1,078",$216,1.0,58.0,2.08,5.0,2.0,120.0,- $150 Pet Fee - 14.45% Tax Will be adjusted i...
102040,57358028,"Room in Queens, NY, near LGA.",56457739998,verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,...,2022.0,$982,$196,1.0,239.0,8.58,2.0,2.0,361.0,1. Please clean-up after yourself in the kitch...

In [113]:
df["host_identity_verified"].str.upper();

In [ ]:
df['host_identity_verified'] = df["host_identity_verified"].str.upper();

              id                                               Name  \
0        1001254                 Clean & quiet apt home by the park
1        1002102                              Skylit Midtown Castle
4        1003689   Entire Apt: Spacious Studio/Loft by central park
5        1004098          Large Cozy 1 BR Apartment In Midtown East
7        1005202                                    BlissArtsSpace!
...          ...                                                ...
102025  57349744       COZY Large Private APARTMENT in EAST VILLAGE
102028  57351400  Gorgeous condo 20min from NYC,close to the air...
102029  57351953             Cozy room in a 2B with backyard access
102031  57353057                       Cozy bedroom in williamsburg
102040  57358028                      Room in Queens, NY, near LGA.

            host id host_identity_verified host name neighbourhood group  \
0       80014485718            UNCONFIRMED  Madaline            Brooklyn
1       52335172823               VERIFIED     Jenna           Manhattan
4       92037596077               VERIFIED    Lyndon           Manhattan
5       45498551794               VERIFIED  Michelle           Manhattan
7       90821839709            UNCONFIRMED      Emma            Brooklyn
...             ...                    ...       ...                 ...
102025  97186426683               VERIFIED      Luna           Manhattan
102028  27226581142            UNCONFIRMED    Arthur              Queens
102029   5155155913            UNCONFIRMED  Cristina              Queens
102031  83101851929               VERIFIED   Russell            Brooklyn
102040  56457739998               VERIFIED     Sonia              Queens

             neighbourhood       lat      long        country  ...  \
0               Kensington  40.64749 -73.97237  United States  ...
1                  Midtown  40.75362 -73.98377  United States  ...
4              East Harlem  40.79851 -73.94399  United States  ...
5              Murray Hill  40.74767 -73.97500  United States  ...
7       Bedford-Stuyvesant  40.68688 -73.95596  United States  ...
...                    ...       ...       ...            ...  ...
102025        East Village  40.72588 -73.98598  United States  ...
102028           Rego Park  40.72999 -73.86043  United States  ...
102029             Astoria  40.76987 -73.92679  United States  ...
102031        Williamsburg  40.70870 -73.96710  United States  ...
102040       East Elmhurst  40.76245 -73.87938  United States  ...

       Construction year    price service fee minimum nights  \
0                 2020.0    $966        $193            10.0
1                 2007.0    $142         $28            30.0
4                 2009.0    $204         $41            10.0
5                 2013.0    $577        $115             3.0
7                 2009.0  $1,060        $212            45.0
...                  ...      ...         ...            ...
102025            2003.0    $878        $176             6.0
102028            2008.0    $994        $199             2.0
102029            2018.0    $822        $164             1.0
102031            2020.0  $1,078        $216             1.0
102040            2022.0    $982        $196             1.0

        number of reviews reviews per month review rate number  \
0                     9.0              0.21                4.0
1                    45.0              0.38                4.0
4                     9.0              0.10                3.0
5                    74.0              0.59                3.0
7                    49.0              0.40                5.0
...                   ...               ...                ...
102025               22.0              0.87                2.0
102028               67.0              2.58                5.0
102029                9.0              0.91                3.0
102031               58.0              2.08                5.0
102040              239.0              8.58                2.0

        calculated host listings count  availability 365  \
0                                  6.0             286.0
1                                  2.0             228.0
4                                  1.0             289.0
5                                  1.0             374.0
7                                  1.0             219.0
...                                ...               ...
102025                             1.0              15.0
102028                             1.0             278.0
102029                             1.0               0.0
102031                             2.0             120.0
102040                             2.0             361.0

                                              house_rules
0       Clean up and treat the home the way you'd like...
1       Pet friendly but please confirm with me if the...
4       Please no smoking in the house, porch or on th...
5                       No smoking, please, and no drugs.
7       House Guidelines for our BnB We are delighted ...
...                                                   ...
102025                                No Smoking, No Pets
102028  1. Be respectful of me and my home 2. No Pets ...
102029   I have other roommates so be respectful of that.
102031  - $150 Pet Fee - 14.45% Tax Will be adjusted i...
102040  1. Please clean-up after yourself in the kitch...

[39420 rows x 24 columns]

In [117]:
df

,id,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,2020.0,$966,$193,10.0,9.0,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,2007.0,$142,$28,30.0,45.0,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,2009.0,$204,$41,10.0,9.0,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,2013.0,$577,$115,3.0,74.0,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs."
7,1005202,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,2009.0,"$1,060",$212,45.0,49.0,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102025,57349744,COZY Large Private APARTMENT in EAST VILLAGE,97186426683,VERIFIED,Luna,Manhattan,East Village,40.72588,-73.98598,United States,...,2003.0,$878,$176,6.0,22.0,0.87,2.0,1.0,15.0,"No Smoking, No Pets"
102028,57351400,"Gorgeous condo 20min from NYC,close to the air...",27226581142,UNCONFIRMED,Arthur,Queens,Rego Park,40.72999,-73.86043,United States,...,2008.0,$994,$199,2.0,67.0,2.58,5.0,1.0,278.0,1. Be respectful of me and my home 2. No Pets ...
102029,57351953,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,...,2018.0,$822,$164,1.0,9.0,0.91,3.0,1.0,0.0,I have other roommates so be respectful of that.
102031,57353057,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,...,2020.0,"$1,078",$216,1.0,58.0,2.08,5.0,2.0,120.0,- $150 Pet Fee - 14.45% Tax Will be adjusted i...
102040,57358028,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,...,2022.0,$982,$196,1.0,239.0,8.58,2.0,2.0,361.0,1. Please clean-up after yourself in the kitch...

In [130]:
df["instant_bookable"].apply(lambda x:1 if x == True else 0);

In [ ]:
df = df["instant_bookable"].apply(lambda x:1 if x == True else 0);

In [134]:
df.reset_index()

,index,id,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,...,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,...,2020.0,$966,$193,10.0,9.0,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1,1002102,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,...,2007.0,$142,$28,30.0,45.0,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,...,2009.0,$204,$41,10.0,9.0,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
3,5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,...,2013.0,$577,$115,3.0,74.0,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs."
4,7,1005202,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,...,2009.0,"$1,060",$212,45.0,49.0,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39415,102025,57349744,COZY Large Private APARTMENT in EAST VILLAGE,97186426683,VERIFIED,Luna,Manhattan,East Village,40.72588,-73.98598,...,2003.0,$878,$176,6.0,22.0,0.87,2.0,1.0,15.0,"No Smoking, No Pets"
39416,102028,57351400,"Gorgeous condo 20min from NYC,close to the air...",27226581142,UNCONFIRMED,Arthur,Queens,Rego Park,40.72999,-73.86043,...,2008.0,$994,$199,2.0,67.0,2.58,5.0,1.0,278.0,1. Be respectful of me and my home 2. No Pets ...
39417,102029,57351953,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,...,2018.0,$822,$164,1.0,9.0,0.91,3.0,1.0,0.0,I have other roommates so be respectful of that.
39418,102031,57353057,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,...,2020.0,"$1,078",$216,1.0,58.0,2.08,5.0,2.0,120.0,- $150 Pet Fee - 14.45% Tax Will be adjusted i...
39419,102040,57358028,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,...,2022.0,$982,$196,1.0,239.0,8.58,2.0,2.0,361.0,1. Please clean-up after yourself in the kitch...